//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PN.App_Data.Languages.Resourse", typeof(Resourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Usuario.
        /// </summary>
        public static string AccountTitles {
            get {
                return ResourceManager.GetString("AccountTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foros.
        /// </summary>
        public static string ForumTitles {
            get {
                return ResourceManager.GetString("ForumTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string HomeTitles {
            get {
                return ResourceManager.GetString("HomeTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        public static string PoliciesTitles {
            get {
                return ResourceManager.GetString("PoliciesTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulos.
        /// </summary>
        public static string PostTitles {
            get {
                return ResourceManager.GetString("PostTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas.
        /// </summary>
        public static string TagTitles {
            get {
                return ResourceManager.GetString("TagTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string UserTitles {
            get {
                return ResourceManager.GetString("UserTitles", resourceCulture);
            }
        }
    }
}
